trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - '*'
    exclude:
      - solutionItems/*
      - 'README.md'


variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 3.1.x
        - script: dotnet restore
          displayName: 'Restore Projects'
        - task: DotNetCoreCLI@2
          displayName: 'Build Projects'
          inputs:
            command: build
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Run Tests'
          inputs:
            command: test
            projects: '**/*Test*.csproj'
            arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
            nobuild: true
        - script: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            reportgenerator -reports:$(Build.SourcesDirectory)/**/*Test.Unit*/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura
          displayName: 'Create Code Coverage Report'
        - task: PublishCodeCoverageResults@1
          displayName: 'Publish Code Coverage Report'
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
            reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'